version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app  # Adjust based on your EC2 setup
permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user