version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building application..."
      - npm run build || echo "No build step"

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'
  discard-paths: no